application: the-amigo
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /js
  static_dir: js

- url: /static
  static_dir: static_files
- url: .*
  script: main.app
  login: required


libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
